module Ir
    ( Identifier
    , Id
    , Field
    , Param
    , Type(..)
    , Lifetime(..)
    , Construct(..)
    , Expr(..)
    , MemType(..)
    , generateIr
    , isUnit
    , isLifetimeLocal
    , functionConstructToType
    , getFunctionParamsType
    , isBorrowedOrOwnedType
    , isBorrowedType
    , isOwnedType
    , prettyShowIr
    , isFunction
    , getFunctionReturnType
    )
    where

import qualified Ast
import qualified Data.Map as Map
import Data.Map (Map)
import Control.Monad.State
import Data.Bifunctor

isFunction :: Construct -> Bool
isFunction construct = case construct of
    Function {} -> True
    _ -> False

getFunctionReturnType :: Type -> Type
getFunctionReturnType type' = case type' of
    Ir.FunctionT _ rt -> rt
    _ -> undefined

getFunctionParamsType :: Type -> [Type]
getFunctionParamsType type' = case type' of
    Ir.FunctionT params _ -> params
    _ -> undefined

isBorrowedOrOwnedType :: Type -> Bool
isBorrowedOrOwnedType type' = isBorrowedType type' || isOwnedType type'

isBorrowedType :: Type -> Bool
isBorrowedType type' = case type' of
    Ir.BorrowedT _ _ -> True
    _ -> False

isOwnedType :: Ir.Type -> Bool
isOwnedType type' = case type' of
    Ir.OwnedT _ -> True
    _ -> False

-- I think the IR should be rather low level but still support functional abstractions
-- Maybe we should be more specific with borrow and mutate and add more intrinsics
-- The IR can be designed to have multiple stages. For example we can include pointers even if
-- they are only used to optimize the output code and not useful for static analyis.

prettyShowIr :: [Construct] -> String
prettyShowIr constructs = unlines $ map show constructs

-- The context required for the translation of the AST to the IR 
data Context = Context
    { getLambdaIndex :: Int
    , getConstructs :: [Construct]
    , getFunctionMap :: Map Identifier Type
    }

-- Utility functions for the context
incrementLambdaIndex :: Context -> Context
incrementLambdaIndex context =
    context { getLambdaIndex = getLambdaIndex context + 1 }

addConstruct :: Construct -> Context -> Context
addConstruct construct context =
    context { getConstructs = construct : getConstructs context }

addFunction :: Identifier -> Type -> Context -> Context
addFunction identifier type' context =
    let newMap = Map.insert identifier type' $ getFunctionMap context in
    context { getFunctionMap = newMap }

type Identifier = String
type Id = Int
type Field = (Identifier, Type)
type Param = (Identifier, Type)

-- Need some rules on how this will be passed into the codegenerator, what will be a pointer and what a value:
-- All basic types like IntT get passed by value
-- String gets passed by value but sliced when borrowed
-- Records are passed by pointer if they are larger than 24 bytes
data Type 
    = UnitT
    | BoolT
    | IntT
    | StringT
    | StringSliceT

    | FunctionT [Type] Type -- Used mostly for externals and for lookup tables in the analyzer and code generator

    -- Used for compile time memory management
    -- After analysis types will have one of these tags
    -- At the start most will be ambiguous and some will be guranteed to be owned
    -- After we figure out what is owned then we can start using borrows
    -- Both of these types get erased before being passed into the code generator as values or pointers
    | BorrowedT Lifetime Type
    | OwnedT Type

    | RefT Type -- Pointer
    | RecordT Identifier

    -- We can use integer ids for lambdas since they are generated by the compiler
    | ClosureT Id -- When lambdas are inlinded we don't need a function pointer and we can just pass the closure 
    | LambdaT Id -- Classic lambdas that hold the data and a function pointer in a struct
    deriving Show

data Lifetime
    = Global -- For global values, can be returned
    | Foreign -- For function parameters, removed the int since it depends on the context
    | Local -- For borrows in of values in the function scope, can't be returned
    deriving Show

isLifetimeLocal :: Lifetime -> Bool
isLifetimeLocal lt = case lt of
    Local -> True
    _ -> False

data Construct
    = Function Identifier [Param] Type Expr
    | Extern Identifier Type
    | Constant Identifier Type Expr
    | Record Identifier [Field]
    | Lambda Id [Field] [Param] Type Expr -- id capturedVariables params retType body
    deriving Show

functionConstructToType :: Construct -> Type
functionConstructToType c = case c of
    Function _ params retType _ -> FunctionT (map snd params) retType
    _ -> undefined

data MemType = Heap | Arena

data Expr
    -- These are useful for tail recursion later
    = Label String
    | Jump String

    | Cond Expr Expr Expr -- condition trueBranch falseBranch

    -- These are used to chain expressions into something resembling procedural code
    | Chain Expr Expr

    -- Literals
    | StringL String
    | StringSliceL String
    | IntL Int
    | BoolL Bool
    | UnitL

    -- Captures locals and makes a lambda
    | Capture Id

    -- Memory allocation instructions
    | Drop [Identifier]

    -- Passing values values
    | Borrow Identifier -- This never gets to the code generator

    | Move Identifier
    | Clone Identifier -- TODO: Should used MemType
    | Ref Identifier
    | Slice Identifier

    | Def Identifier Type Expr -- Creates a new value returns Unit
    | Mutate Identifier Expr -- Changes the value of a variable returns Unit

    -- Execute functions
    | Run Identifier [Expr]
    | RunLambda Expr [Expr]
    deriving Show

generateIr :: [Ast.Binding] -> [Construct]
generateIr bindings = getConstructs $ execState (generateConstructs bindings) context
    where
        context = Context 0 [] Map.empty

generateConstructs :: [Ast.Binding] -> State Context ()
generateConstructs bindings = case bindings of
    (Ast.Extern name type' : xs) -> do
        let exType = astTypeToIrTypeEx False type'
        modify $ addFunction name exType
        modify $ addConstruct $ Extern name exType
        generateConstructs xs

    (Ast.Binding name type' expr : xs) -> case type' of
        Ast.FunctionT _ retType -> do
            let (lambdaParams, lambdaExpr) = extractLambda expr
            let params = map (second astTypeToIrType) lambdaParams
            functionBody <- generateExpr lambdaExpr
            modify $ addFunction name (astTypeToIrType type')
            modify $ addConstruct $ Function name params (astTypeToIrType retType) functionBody
            generateConstructs xs
        _ -> do
            resExpr <- generateExpr expr
            modify $ addConstruct $ Constant name (astTypeToIrType type') resExpr
            generateConstructs xs

    [] -> pure ()
    where
        extractLambda expr = case expr of
            Ast.Lambda params _ expr' -> (params, expr')
            _ -> undefined

generateExpr :: Ast.Expr -> State Context Expr
generateExpr expr = case expr of
    Ast.UnitL -> pure UnitL
    Ast.IntL n -> pure $ IntL n
    Ast.StringL s -> pure $ StringL s
    Ast.Get name -> pure $ Clone name

    Ast.Let name type' action cont -> do
        actionExpr <- generateExpr action
        contExpr <- generateExpr cont
        pure $ Chain (Def name (astTypeToIrType type') actionExpr) contExpr

    Ast.Do action cont -> do
        actionExpr <- generateExpr action
        contExpr <- generateExpr cont
        pure $ Chain actionExpr contExpr

    -- Lets not worry about capturing for now
    Ast.Lambda params retType lexpr -> do
        lambdaId <- gets getLambdaIndex
        modify $ incrementLambdaIndex
        lambdaExpr <- generateExpr lexpr
        let lambdaParams = map (second astTypeToIrType) params
        let lambdaConstruct = Lambda lambdaId [] lambdaParams (astTypeToIrType retType) lambdaExpr
        modify $ addConstruct lambdaConstruct
        pure $ Capture lambdaId

    -- Needs to check if a function is a lambda or a normal function and run accordingly
    -- TODO: Should be a separate pass where we change RunLambda to Run based on if it is a function
    Ast.Call callExpr params -> do
        callParams <- mapM generateExpr params
        lambdaExpr <- generateExpr callExpr
        pure $ RunLambda lambdaExpr callParams

astTypeToIrType :: Ast.Type -> Type
astTypeToIrType type' = case type' of
    Ast.UnitT -> UnitT
    Ast.IntT -> IntT
    Ast.StringT -> StringT
    Ast.FunctionT params retType -> FunctionT (map astTypeToIrType params) (astTypeToIrType retType)
    Ast.OwnedT innerType -> OwnedT $ astTypeToIrType innerType

astTypeToIrTypeEx :: Bool -> Ast.Type -> Type
astTypeToIrTypeEx isParam type' = case type' of
    Ast.UnitT -> BorrowedT lifetime UnitT
    Ast.IntT -> BorrowedT lifetime IntT
    Ast.StringT -> BorrowedT lifetime StringT
    Ast.FunctionT params retType -> FunctionT (map (astTypeToIrTypeEx True) params) (astTypeToIrTypeEx False retType)
    Ast.OwnedT innerType -> OwnedT $ astTypeToIrType innerType
    where
        lifetime = if isParam then Foreign else Global

isUnit :: Type -> Bool
isUnit type' = case type' of
    UnitT -> True
    _ -> False

-- How does interop with c work when we don't know if the C code takes a reference or an owned value?
-- I think we have to just pass everything by reference and just ask people to not modify the value...
-- At least for external c interop. Compiler builtins are special since the compiler understands them.

-- For fun lets try to hand compile this program
-- No optimization

{-
myCompiledIr
    = Extern "ng_printLn" (FunctionT [StringSliceT] UnitT)
    : Extern "ng_addInt" (FunctionT [IntT, IntT] IntT)
    : Extern "ng_subInt" (FunctionT [IntT, IntT] IntT)
    : Extern "ng_eqInt" (FunctionT [IntT, IntT] BoolT)

    : Constant "aString" StringT (StringL "Hello, Great Queen Lyra!\\n")
    : Constant "anInt" IntT (IntL 10)

    : Function "main" [] UnitT 
        (Chain (Run "ng_printLn" [Slice "aString"])
        (Chain (Def "ls" StringT (StringL "You look lovely today!"))
        (Chain (Run "testMath" [IntL 10, IntL 4])
        (Chain (Cond (BoolL True) (IntL 10) (IntL 20))
        (Chain (Run "ng_printLn" [StringSliceL "You look great!"]) (Drop ["ls"])
        )))))

    : Function "testMath" [("a", IntT), ("b", IntT)] IntT
        (Run "ng_addInt" [Clone "a", Run "ng_subInt" [IntL 10, Clone "b"]])

    : Function "testFunc" [("x", BoolT)] IntT
        (Cond (Clone "x") (IntL 10) (IntL 20))

    : Function "fibonacci" [("i", IntT)] IntT
        (Cond (Run "ng_eqInt" [Clone "i", IntL 0]) (IntL 0)
        (Cond (Run "ng_eqInt" [Clone "i", IntL 1]) (IntL 1)
            (Run "ng_addInt" 
                [Run "fibonacci" [Run "ng_subInt" [Clone "i", IntL 1]],
                 Run "fibonacci" [Run "ng_subInt" [Clone "i", IntL 2]]]
        )))

    : Function "fib" [("n", IntT)] IntT
        (Run "_fib" [Clone "n", IntL 0, IntL 1, IntL 0])

    : Function "_fib" [("n", IntT), ("a", IntT), ("b", IntT), ("index", IntT)] IntT
        (Chain (Label "tailcall")
        (Cond (Run "ng_eqInt" [Clone "index", Clone "n"]) (Clone "a")
        (Chain (Def "c" IntT (Clone "a"))
        (Chain (Mutate "a" (Clone "b"))
        (Chain (Mutate "b" (Run "ng_addInt" [Clone "c", Clone "b"]))
        (Chain (Mutate "index" (Run "ng_addInt" [Clone "index", IntL 1]))
        (Jump "tailcall")
        ))))))
        
    : []
-}
